apiVersion: cluster.x-k8s.io/v1beta1
name: argocd-test-cluster
kcpCount: 1
workerCount: 1
clusterClass: builtin-generic-v3.3.0
vmClass: best-effort-medium
storageClass: worker-storagepolicy
krVersion: v1.34.2+vmware.2-vkr.2
osName: ubuntu
osVersion: 22.04
