---
apiVersion: v1
kind: Secret
metadata:
  name: secret-name
stringData:
  user-data: |
    #cloud-config
    repo_update: true
    repo_upgrade: all

    password: VMWARE
    ssh_pwauth: true

    users:
    - name: vmware
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: false
      # Password set to VMuno!23
      passwd: '$5$1SX7BjP5Mc6AB$sxKzSEVN2tbI3HeasygCo4lUEtJ.iY8dmqW6hZKvUW3'
      shell: /bin/bash
