apiVersion: dataprotection.management.kubernetes.vmware.com/v1alpha1
kind: ClusterBackupLocationCredential
metadata:
  name: yyyy
  namespace: '@org'
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  provider: AmazonS3
  keyValueSecretData:
    - key: aws_access_key_id
      value: bWluaW9hZG1pbg==
    - key: aws_secret_access_key
      value: bWluaW9hZG1pbg==
