apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: vks-project-ns-lml9d
    namespace: vks-project-ns-lml9d
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/luwangVMW/magicblocks.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
