apiVersion: v1
kind: Secret
metadata:
  name: test
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: test
  server: https://kubernetes.default.svc/?context=test
  namespaces: test-ns-1-pspbb
  clusterResources: "false"
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6InYtZmJUUWQ0bWZFUnA4VmRiUTNkc2pNVFV5RWJlM2VGa3JoR0RRSEFHR0kifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ2a3MtcHJvamVjdC1ucy1sbWw5ZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcmdvY2QtaW5zdGFuY2Utc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXJnb2NkLWluc3RhbmNlLXNhIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNTI3N2Q4ZDktMjVjMy00NjlhLWE5NDUtOWM0MmMzZWZkMjY3Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnZrcy1wcm9qZWN0LW5zLWxtbDlkOmFyZ29jZC1pbnN0YW5jZS1zYSJ9.JPtmPLx01P7Ur2ji3BMYGLf2mZs6rsAVnT-obLrnhpB1R21O8mIJA0SRmNDwPMm99_OlW0_EkeA6hovdmGfnn3zeg8nu6fQJp94RPXPAD5s2qF-bMvbteKANSrXXyQTVzf_VUTI26oLYow776EZyjgpz87wjhNSSB31lSgREm9SDgucfN2JIR-RtPcJDvw8IXdXZKqw2DuUGaEOctm9wVd3TzzcFhv5trU2mw3CPPit7txWRhGemePzM7_T1ZhDvprWu9qMVT52Hi9TROIntdLpbseUoFg1OdLA2DjS0uiKqtmYhVK9gyPoSl7PYopjkcBLmYQ9_pu8UMPnjJw5PAxYQAbOfuC6MLb9F7h1xeQOb8hJgJH3GDHwFxMOtqwmOU7nnx-JAIDXoxwauz5lsBsGNoLTPluEXWQrYDQJtNhzwgCc40dZNcVJz6NmwjIIQxS5vb07-P0zhjwJKMkitCxBfEJd2nVsoftRpQ7LC81pVVVlE8hFBEDekSd6BMpke",
      "tlsClientConfig": {
        "insecure": true
      }
    }
