apiVersion: infrastructure.cci.vmware.com/v1alpha2
kind: SupervisorNamespaceClassConfig
metadata:
  name: test-class-config
spec:
  vmClasses:
    - name: best-effort-xsmall
  storageClasses:
    - name: wcpglobal_storage_profile
      limit: 1024Mi
  contentSources: []
  zones:
    - name: '*'
      cpuLimit: 2000M
      cpuReservation: 0M
      memoryLimit: 2024Mi
      memoryReservation: 0Mi
