apiVersion: vmoperator.vmware.com/v1alpha5
kind: VirtualMachine
metadata:
  name:      test-vm1
spec:
  className:    best-effort-xsmall
  imageName:    vmi-70bad6e1bd47f6d7c # k get osimage
  storageClass: wcpglobal-storage-profile
  bootstrap: #
    cloudInit:
      cloudConfig: {}
