apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  name:      test-vm1
spec:
  className:    best-effort-xsmall
  imageName:    vmi-7134489cfe37ffca8
  storageClass: wcpglobal_storage_profile
  bootstrap: #
    cloudInit:
      cloudConfig: {}
