apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  name:      test-vm1
spec:
  className:    best-effort-large
  imageName:    photon-5-amd64-v1.32.0---vmware.6-fips-vkr.2 
  storageClass: wcpglobal-storage-profile
  bootstrap: #
    cloudInit:
      cloudConfig: {}
